#
# Copyright 2023- IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#
name: CI
on:
  pull_request:
  push:
    branches:
    - main
    tags:
    - v*
            
jobs:
  Build:
    strategy:
      fail-fast: true
      matrix:
        include:
          # Spark 3.1.x
          - hadoop: 3.2.0
            scala: 2.12.15
          - hadoop: 3.2.0
            scala: 2.13.5
          # Spark 3.2.x
          - hadoop: 3.3.1
            scala: 2.12.15
          - hadoop: 3.3.1
            scala: 2.13.5
          # Spark 3.3.x
          - hadoop: 3.3.2
            scala: 2.12.15
          - hadoop: 3.3.2
            scala: 2.13.8
          # SPark 3.4.x
          - hadoop: 3.3.4
            scala: 2.12.17
          - hadoop: 3.3.4
            scala: 2.13.8
    runs-on: ubuntu-latest
    env:
      HADOOP_VERSION: ${{ matrix.hadoop }}
      SCALA_VERSION: ${{ matrix.scala }}
      GEDS_VERSION: "1.0"
      GEDS_INSTALL: ${{ github.workspace }}/geds
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: sbt
    - name: Prepare build
      shell: bash
      run: ./.github/prepare-build.sh
    - name: Package
      shell: bash
      run: |
        sbt package
    - name: Upload release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: target/scala*/*.jar
